server:
  port: 13400

spring:
  application:
    name: module-batch
  profiles:
    active: development
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    hikari:
      autoCommit: true
      maximumPoolSize: 100
      minimumIdle: 10
      connectionTestQuery: SELECT 1

  sql:
    init:
      encoding: UTF-8

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show_sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  rabbitmq:
    host: localhost
    port: 12000
    username: guest
    password: guest
    template:
      reply-timeout: 30000

  redis:
    host: localhost
    port: 11000
    password: 123456
    timeout: 2000
    lettuce:
      shutdown-timeout: 2000
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 1

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health

  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true

app:
  rabbitMQ:
    exchange: keyword.exchange
    queue: keyword.queue
    routing: keyword.routingKey.#